<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 
    Este proyecto es un proyecto hijo de otro proyecto.
    He de indicar aqui el proyecto padre
    -->
    <parent>
        <groupId>com.curso.diccionarios_v1</groupId>
        <artifactId>diccionarios_v1</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>diccionarios-gestion-impl-bbdd</artifactId>
    <version>1.0.0</version>

    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-gestion-api</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-en-bbdd</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- SpringBoot: Web-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.46</version>
            <scope>provided</scope> <!-- Es una dependencia que solo se usa en tiempo de compilacion, no en tiempo de ejecucion -->
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <!-- forzar a que se use el procesador de anotaciones de Lombok -->
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.46</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>