<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 
    Este proyecto es un proyecto hijo de otro proyecto.
    He de indicar aqui el proyecto padre
    -->
    <parent>
        <groupId>com.curso.diccionarios_v1</groupId>
        <artifactId>diccionarios_v1</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>aplicacion-servidor</artifactId>
    <version>1.0.0</version>

    <packaging>jar</packaging>

    <dependencies>

        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-gestion-impl-ficheros</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-rest-impl</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionario-espanol</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>cargador-bbdd</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <!-- BOM: Bill of Materials. Es un proyecto que contiene las versiones de las librerias que necesita otra libreria -->
            <!-- Lo suyo sería no definir la versión de Springboot aqui. Sino definirla en un BOM a nivel del proyecto padre -->
            <!-- En un rato lo hacemos: REFACTORIZACION -->
            <version>4.1.0</version>
        </dependency>
        <!-- Metemos swagger / springdoc-->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>3.1.0</version>
        </dependency>
    </dependencies>

    <!-- 
        Para arrancar fácilmente la aplicación Spring, puedo usar un plugin que ofrece la gente de Spring 
        Para ejecutarla solo escribiré en la terminal: mvn spring-boot:run
    -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>4.1.0</version>
            </plugin>
        </plugins>
    </build> 

</project>