<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 
    Este proyecto es un proyecto hijo de otro proyecto.
    He de indicar aqui el proyecto padre
    -->
    <parent>
        <groupId>com.curso.diccionarios_v1</groupId>
        <artifactId>diccionarios_v1</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>cargador-bbdd</artifactId>
    <version>1.0.0</version>

    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-en-bbdd</artifactId>
            <version>1.0.0</version><!-- Este me da los repos, para poder hacer las inserciones -->
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <!-- BOM: Bill of Materials. Es un proyecto que contiene las versiones de las librerias que necesita otra libreria -->
            <!-- Lo suyo sería no definir la versión de Springboot aqui. Sino definirla en un BOM a nivel del proyecto padre -->
            <!-- En un rato lo hacemos: REFACTORIZACION -->
            <version>4.1.0</version>
        </dependency>


        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.46</version>
            <scope>provided</scope> <!-- Es una dependencia que solo se usa en tiempo de compilacion, no en tiempo de ejecucion -->
        </dependency>
    </dependencies>


</project>