<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 
    Este proyecto es un proyecto hijo de otro proyecto.
    He de indicar aqui el proyecto padre
    -->
    <parent>
        <groupId>com.curso.diccionarios_v1</groupId>
        <artifactId>diccionarios_v1</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>diccionarios-gestion-impl-rest</artifactId>
    <version>1.0.0</version>

    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-gestion-api</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.curso.diccionarios_v1</groupId>
            <artifactId>diccionarios-rest-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- Meter la libreria GSON para poder deserializar el JSON que viene del servidor REST a un objeto de tipo RespuestaPalabraDTO -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>
    </dependencies>
</project>